# Generated by Django 5.2 on 2025-04-20 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
