# Generated by Django 5.2 on 2025-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
