# Generated by Django 5.2 on 2025-04-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_team_description_alter_team_name_and_more'),
        ('todo_list', '0002_alter_team_name_alter_todo_description_and_more'),
    ]

    operations = [
    ]
