# Generated by Django 5.2 on 2025-04-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_todo_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
    ]
